import { useEffect, useMemo, useState } from 'react';
import * as Icon from 'lucide-react';
import type { AppSettings, OperationEvent, OperationRecord, ToolDefinition, ToolResult } from '@shared/contracts';
import { dictionaries, direction, type Locale } from './locales';

const categoryNav = [
  ['home', 'nav.home', 'LayoutDashboard'], ['scan', 'nav.scan', 'ScanSearch'], ['storage', 'nav.storage', 'HardDrive'], ['files', 'nav.files', 'FolderOpen'], ['cleanup', 'nav.cleanup', 'Trash2'], ['startup', 'nav.startup', 'Rocket'], ['applications', 'nav.apps', 'AppWindow'], ['system', 'nav.system', 'Activity'], ['network', 'nav.network', 'Network'], ['hardware', 'nav.hardware', 'Cpu'], ['history', 'nav.history', 'History'], ['settings', 'nav.settings', 'Settings']
] as const;

function formatBytes(value: unknown, locale: Locale) { const n = Number(value); if (!Number.isFinite(n) || n < 0) return '—'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; let index = 0; let amount = n; while (amount >= 1024 && index < units.length - 1) { amount /= 1024; index++; } return `${new Intl.NumberFormat(locale === 'ar' ? 'ar' : 'en', { maximumFractionDigits: index > 1 ? 1 : 0 }).format(amount)} ${units[index]}`; }
function formatDuration(seconds: unknown, locale: Locale) { const n = Number(seconds); if (!Number.isFinite(n)) return '—'; const hours = Math.floor(n / 3600); const minutes = Math.floor((n % 3600) / 60); return new Intl.NumberFormat(locale === 'ar' ? 'ar' : 'en').format(hours) + ':' + String(minutes).padStart(2, '0'); }
function translate(locale: Locale, key: string) { return dictionaries[locale][key] || key; }

export default function App() {
  const [tools, setTools] = useState<ToolDefinition[]>([]); const [settings, setSettings] = useState<AppSettings | null>(null); const [page, setPage] = useState('home'); const [selected, setSelected] = useState<ToolDefinition | null>(null); const [folder, setFolder] = useState(''); const [file, setFile] = useState(''); const [query, setQuery] = useState(''); const [event, setEvent] = useState<OperationEvent | null>(null); const [result, setResult] = useState<ToolResult | null>(null); const [history, setHistory] = useState<OperationRecord[]>([]); const [health, setHealth] = useState<Record<string, unknown> | null>(null); const [operationOpen, setOperationOpen] = useState(false); const [notice, setNotice] = useState('');
  const locale = settings?.localization.locale || 'ar'; const t = (key: string) => translate(locale, key);
  useEffect(() => { document.documentElement.lang = locale; document.documentElement.dir = direction(locale); document.documentElement.dataset.theme = settings?.appearance.theme || 'dark'; document.documentElement.style.setProperty('--font-scale', String(settings?.appearance.fontScale || 1)); }, [locale, settings]);
  useEffect(() => { Promise.all([window.knoux.listTools(), window.knoux.getSettings(), window.knoux.listHistory()]).then(([toolList, appSettings, records]) => { setTools(toolList); setSettings(appSettings); setHistory(records); const healthTool = toolList.find(tool => tool.id === 'system-health'); if (healthTool) run(healthTool, {}, true); }).catch(error => setNotice(String(error?.message || error))); return window.knoux.onOperationEvent(next => { setEvent(next); if (next.result) { setResult(next.result); setHistory(records => [{ ...next.result!, action: next.toolId, durationMs: Date.now() - new Date(next.result!.startedAt).getTime(), undoAvailable: false }, ...records.filter(item => item.operationId !== next.operationId)]); if (next.toolId === 'system-health' && next.result.success) setHealth(next.result.summary); } if (['queued', 'running', 'progress'].includes(next.phase)) setOperationOpen(true); }); }, []);
  const visibleTools = useMemo(() => tools.filter(tool => { const haystack = `${t(tool.nameKey)} ${t(tool.descriptionKey)} ${tool.category}`.toLowerCase(); const categoryMatch = !['home', 'history', 'settings', 'scan'].includes(page) ? tool.category === page : page === 'scan' ? tool.id === 'smart-scan' : true; return categoryMatch && haystack.includes(query.toLowerCase()); }), [tools, page, query, locale]);
  const active = event && ['queued', 'preflight', 'running', 'progress'].includes(event.phase) ? event : null;
  async function chooseFolder() { const chosen = await window.knoux.chooseFolder(); if (chosen) setFolder(chosen); }
  async function chooseFile() { const chosen = await window.knoux.chooseFile(); if (chosen) setFile(chosen); }
  async function run(tool: ToolDefinition, override: Record<string, unknown> = {}, silent = false) { setSelected(tool); setResult(null); if (!silent) setOperationOpen(true); const inputs: Record<string, unknown> = { ...override }; if (folder) inputs.folder = folder; if (file) inputs.filePath = file; const completed = await window.knoux.runTool({ toolId: tool.id, inputs }); setResult(completed); if (tool.id === 'system-health' && completed.success) setHealth(completed.summary); }
  async function update(patch: Partial<AppSettings>) { const next = await window.knoux.updateSettings(patch); setSettings(next); setNotice(t('settings.saved')); window.setTimeout(() => setNotice(''), 2500); }
  const navIcon = (name: string) => { const Component = (Icon as unknown as Record<string, React.ComponentType<{ size?: number }>>)[name] || Icon.Circle; return <Component size={18} />; };
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-symbol">K</span><div><strong>{t('app.name')}</strong><small>{t('app.tagline')}</small></div></div><nav aria-label={t('app.name')}>{categoryNav.map(([id, label, icon]) => <button key={id} className={page === id ? 'nav-item active' : 'nav-item'} onClick={() => { setPage(id); setQuery(''); }}><span>{navIcon(icon)}</span>{t(label)}</button>)}</nav><div className="sidebar-foot"><span className="local-badge"><Icon.ShieldCheck size={14} /> {t('common.local')}</span><span className="muted">v0.4.0</span></div></aside><main className="main"><header className="topbar"><div><p className="eyebrow">{t('app.tagline')}</p><h1>{page === 'home' ? t('home.title') : page === 'history' ? t('history.title') : page === 'settings' ? t('settings.title') : t('tools.title')}</h1></div><div className="top-actions"><label className="search"><Icon.Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder={t('tools.search')} aria-label={t('tools.search')} /></label><button className="icon-button" onClick={() => setOperationOpen(true)} aria-label={t('operation.title')}><Icon.ListChecks size={19}/>{active && <i />}</button><button className="locale-button" onClick={() => update({ localization: { ...settings!.localization, locale: locale === 'ar' ? 'en' : 'ar' } })}>{locale === 'ar' ? 'EN' : 'ع'}</button></div></header>{notice && <div className="notice" role="status">{notice}</div>}{page === 'home' ? <Home t={t} locale={locale} health={health} onScan={() => { const tool = tools.find(item => item.id === 'smart-scan'); if (tool) run(tool); }} onTool={tool => { setSelected(tool); setPage(tool.category); }} tools={tools} /> : page === 'settings' ? <Settings t={t} settings={settings} onUpdate={update} /> : page === 'history' ? <History t={t} locale={locale} records={history} /> : <ToolWorkspace t={t} tools={visibleTools} selected={selected} folder={folder} file={file} result={result} onSelect={setSelected} onFolder={chooseFolder} onFile={chooseFile} onRun={run} />}</main>{operationOpen && <OperationDrawer t={t} locale={locale} event={event} result={result} onClose={() => setOperationOpen(false)} onCancel={() => active && window.knoux.cancelOperation(active.operationId)} />}</div>;
}

function Home({ t, locale, health, onScan, onTool, tools }: { t: (k: string) => string; locale: Locale; health: Record<string, unknown> | null; onScan: () => void; onTool: (tool: ToolDefinition) => void; tools: ToolDefinition[] }) { const diskPercent = health?.systemDriveTotalBytes ? Math.round((1 - Number(health.systemDriveFreeBytes) / Number(health.systemDriveTotalBytes)) * 100) : null; const score = health ? Math.max(0, 100 - Math.round((health.memoryUsedPercent as number || 0) * .2) - Math.max(0, (diskPercent || 0) - 75)) : null; return <><section className="hero"><div><span className="local-badge"><Icon.LockKeyhole size={14}/>{t('common.local')}</span><h2>{t('home.health')} <strong>{score === null ? '—' : score}</strong></h2><p>{t('home.subtitle')}</p><button className="primary" onClick={onScan}><Icon.ScanSearch size={18}/>{t('home.scan')}</button></div><div className="health-ring" style={{ '--score': `${score || 0}%` } as React.CSSProperties}><span>{score === null ? '—' : score}</span><small>/100</small></div></section><section className="metric-grid"><Metric label={t('home.memory')} value={health ? `${health.memoryUsedPercent}%` : '—'} detail={health ? `${formatBytes(health.memoryFreeBytes, locale)} ${t('common.noData')}` : t('common.loading')} icon={<Icon.MemoryStick/>}/><Metric label={t('home.storage')} value={health ? formatBytes(health.systemDriveFreeBytes, locale) : '—'} detail={diskPercent === null ? t('common.loading') : `${diskPercent}%`} icon={<Icon.HardDrive/>}/><Metric label={t('home.uptime')} value={health ? formatDuration(health.uptimeSeconds, locale) : '—'} detail={t('home.ready')} icon={<Icon.Timer/>}/><Metric label={t('home.cpu')} value={health?.cpuCores ? String(health.cpuCores) : '—'} detail={String(health?.cpuModel || t('common.loading')).slice(0, 38)} icon={<Icon.Cpu/>}/></section><section className="section"><div className="section-title"><div><h2>{t('tools.title')}</h2><p>{t('home.offline')}</p></div></div><div className="quick-grid">{tools.filter(tool => ['smart-scan','large-files','duplicate-files','temp-cleanup-preview','startup-items','installed-apps'].includes(tool.id)).map(tool => <button className="quick-card" key={tool.id} onClick={() => onTool(tool)}><Icon.Wrench size={18}/><strong>{t(tool.nameKey)}</strong><small>{t(tool.descriptionKey)}</small></button>)}</div></section></> }
function Metric({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: React.ReactNode }) { return <article className="metric"><span className="metric-icon">{icon}</span><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>; }
function ToolWorkspace({ t, tools, selected, folder, file, result, onSelect, onFolder, onFile, onRun }: { t: (k: string) => string; tools: ToolDefinition[]; selected: ToolDefinition | null; folder: string; file: string; result: ToolResult | null; onSelect: (tool: ToolDefinition) => void; onFolder: () => void; onFile: () => void; onRun: (tool: ToolDefinition) => void }) { return <div className="workspace"><section className="catalog panel"><div className="section-title"><div><h2>{t('tools.title')}</h2><p>{tools.length ? t('home.offline') : t('common.noData')}</p></div></div><div className="tool-list">{tools.map(tool => <button className={selected?.id === tool.id ? 'tool-card selected' : 'tool-card'} key={tool.id} onClick={() => onSelect(tool)}><Icon.Wrench size={18}/><span><strong>{t(tool.nameKey)}</strong><small>{t(tool.descriptionKey)}</small></span><label>{t('common.readOnly')}</label></button>)}</div></section><section className="runner panel">{selected ? <><div className="tool-heading"><span><Icon.ShieldCheck size={22}/></span><div><h2>{t(selected.nameKey)}</h2><p>{t(selected.descriptionKey)}</p></div></div>{['large-files','duplicate-files','empty-folders'].includes(selected.id) && <div className="input-group"><label>{t('common.folder')}</label><div><input value={folder} readOnly placeholder={t('tools.defaultFolder')} /><button onClick={onFolder}>{t('tools.chooseFolder')}</button></div></div>}{selected.id === 'file-hash' && <div className="input-group"><label>{t('tools.hashFile')}</label><div><input value={file} readOnly placeholder={t('tools.hashFile')} /><button onClick={onFile}>{t('tools.hashFile')}</button></div></div>}<button className="primary run-button" onClick={() => onRun(selected)}><Icon.Play size={18}/>{t('tools.run')}</button>{result && result.toolId === selected.id && <ResultView t={t} result={result} />}</> : <div className="empty-state"><Icon.MousePointer2 size={30}/><p>{t('tools.noSelection')}</p></div>}</section></div>; }
function ResultView({ t, result }: { t: (k: string) => string; result: ToolResult }) { return <div className={result.success ? 'result result-success' : 'result result-error'}><h3>{result.success ? t('common.result') : t('operation.failed')}</h3>{result.errors.map(error => <p key={error}>{error}</p>)}<dl>{Object.entries(result.summary).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{typeof value === 'object' ? JSON.stringify(value) : String(value ?? '—')}</dd></div>)}</dl>{result.items.length > 0 && <details><summary>{t('operation.items')} ({result.items.length})</summary><pre>{JSON.stringify(result.items.slice(0, 20), null, 2)}</pre></details>}</div>; }
function OperationDrawer({ t, locale, event, result, onClose, onCancel }: { t: (k: string) => string; locale: Locale; event: OperationEvent | null; result: ToolResult | null; onClose: () => void; onCancel: () => void }) { const progress = event?.percent ?? (result ? 100 : 0); const running = event && ['queued','preflight','running','progress'].includes(event.phase); return <aside className="operation-drawer" aria-label={t('operation.title')}><div className="drawer-head"><div><h2>{t('operation.title')}</h2><p>{event?.message || t('operation.ready')}</p></div><button className="icon-button" onClick={onClose} aria-label="close"><Icon.X size={18}/></button></div><div className="progress"><i style={{ width: `${progress}%` }}/></div><div className="operation-meta"><span>{event?.phase || 'idle'}</span><span>{new Intl.NumberFormat(locale === 'ar' ? 'ar' : 'en').format(progress)}%</span></div>{running ? <button className="secondary" onClick={onCancel}><Icon.Ban size={16}/>{t('operation.cancel')}</button> : <p className="drawer-empty">{result ? (result.success ? t('operation.complete') : t('operation.failed')) : t('operation.empty')}</p>}</aside>; }
function Settings({ t, settings, onUpdate }: { t: (k: string) => string; settings: AppSettings | null; onUpdate: (patch: Partial<AppSettings>) => void }) { if (!settings) return <p>{t('common.loading')}</p>; return <section className="settings-page"><p className="page-description">{t('settings.subtitle')}</p><div className="settings-grid"><Setting label={t('settings.language')}><select value={settings.localization.locale} onChange={e => onUpdate({ localization: { ...settings.localization, locale: e.target.value as Locale } })}><option value="ar">العربية</option><option value="en">English</option></select></Setting><Setting label={t('settings.theme')}><select value={settings.appearance.theme} onChange={e => onUpdate({ appearance: { ...settings.appearance, theme: e.target.value as AppSettings['appearance']['theme'] } })}><option value="dark">{t('common.dark')}</option><option value="light">{t('common.light')}</option><option value="system">{t('common.system')}</option></select></Setting><Setting label={t('settings.density')}><select value={settings.appearance.density} onChange={e => onUpdate({ appearance: { ...settings.appearance, density: e.target.value as AppSettings['appearance']['density'] } })}><option value="comfortable">{t('common.comfortable')}</option><option value="compact">{t('common.compact')}</option></select></Setting><Toggle label={t('settings.motion')} checked={settings.appearance.reducedMotion} onChange={checked => onUpdate({ appearance: { ...settings.appearance, reducedMotion: checked } })}/><Toggle label={t('settings.closeTray')} checked={settings.general.closeToTray} onChange={checked => onUpdate({ general: { ...settings.general, closeToTray: checked } })}/><Setting label={t('settings.largeFile')}><input type="number" min="1" value={Math.round(settings.scan.largeFileBytes / 1048576)} onChange={e => onUpdate({ scan: { ...settings.scan, largeFileBytes: Number(e.target.value) * 1048576 } })}/></Setting><Setting label={t('settings.duplicate')}><input type="number" min="1" value={Math.round(settings.scan.minimumDuplicateBytes / 1048576)} onChange={e => onUpdate({ scan: { ...settings.scan, minimumDuplicateBytes: Number(e.target.value) * 1048576 } })}/></Setting></div></section>; }
function Setting({ label, children }: { label: string; children: React.ReactNode }) { return <label className="setting"><span>{label}</span>{children}</label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="setting toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /></label>; }
function History({ t, locale, records }: { t: (k: string) => string; locale: Locale; records: OperationRecord[] }) { return <section><p className="page-description">{t('history.subtitle')}</p>{records.length === 0 ? <div className="empty-state"><Icon.History size={30}/><p>{t('history.empty')}</p></div> : <div className="history-list">{records.map(record => <article key={record.operationId} className="history-card"><div><span className={record.success ? 'status success' : 'status error'}>{record.success ? t('history.success') : t('history.error')}</span><strong>{record.toolId}</strong><small>{new Intl.DateTimeFormat(locale === 'ar' ? 'ar' : 'en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(record.finishedAt))}</small></div><span>{record.items.length}</span></article>)}</div>}</section>; }
