export type Locale = 'ar' | 'en';
export type Dictionary = Record<string, string>;

export const dictionaries: Record<Locale, Dictionary> = {
  ar: {
    'app.name': 'KNOuX SmartOrganizer', 'app.tagline': 'منظّم Windows محلي وآمن', 'nav.home': 'الرئيسية', 'nav.scan': 'الفحص الذكي', 'nav.storage': 'التخزين', 'nav.files': 'الملفات', 'nav.cleanup': 'التنظيف', 'nav.startup': 'بدء التشغيل', 'nav.apps': 'التطبيقات', 'nav.system': 'النظام', 'nav.network': 'الشبكة', 'nav.hardware': 'العتاد', 'nav.history': 'السجل', 'nav.settings': 'الإعدادات',
    'home.title': 'نظرة عامة على الجهاز', 'home.subtitle': 'بيانات محلية مقاسة من Windows، بلا نتائج مصطنعة.', 'home.scan': 'بدء الفحص الذكي', 'home.health': 'صحة النظام', 'home.ready': 'جاهز للفحص', 'home.offline': 'الوظائف الأساسية تعمل دون اتصال بالإنترنت', 'home.memory': 'استخدام الذاكرة', 'home.storage': 'مساحة قرص النظام', 'home.uptime': 'وقت التشغيل', 'home.cpu': 'المعالج',
    'tools.title': 'الأدوات المتاحة', 'tools.search': 'ابحث عن أداة أو فئة', 'tools.run': 'تشغيل الأداة', 'tools.chooseFolder': 'اختيار مجلد', 'tools.journal': 'معرّف سجل التراجع', 'confirm.organize': 'راجعت المعاينة وأؤكد نقل الملفات الظاهرة فقط.', 'tools.defaultFolder': 'المجلد الافتراضي: مجلد المستخدم', 'tools.noSelection': 'اختر أداة لعرض وصفها وتشغيلها.', 'tools.openHistory': 'فتح السجل', 'tools.requiresFolder': 'يتطلب اختيار مجلد', 'tools.hashFile': 'اختيار ملف للحساب',
    'operation.title': 'مركز العمليات', 'operation.ready': 'لا توجد عملية نشطة', 'operation.cancel': 'إلغاء العملية', 'operation.complete': 'اكتملت العملية', 'operation.failed': 'تعذر تنفيذ العملية', 'operation.empty': 'ستظهر العمليات الحقيقية هنا أثناء تنفيذها.', 'operation.items': 'عناصر النتيجة',
    'settings.title': 'الإعدادات', 'settings.subtitle': 'تُحفظ الإعدادات محلياً على الجهاز. لا توجد تحليلات استخدام أو تقارير أعطال افتراضية.', 'settings.language': 'لغة التطبيق', 'settings.theme': 'السمة', 'settings.density': 'كثافة الواجهة', 'settings.motion': 'تقليل الحركة', 'settings.largeFile': 'حد الملفات الكبيرة', 'settings.duplicate': 'أصغر حجم لتكرارات الملفات', 'settings.closeTray': 'الإغلاق إلى شريط المهام', 'settings.saved': 'تم حفظ الإعدادات',
    'history.title': 'سجل العمليات', 'history.subtitle': 'نتائج فعلية ومحفوظة محلياً؛ لا توجد أمثلة أو نتائج وهمية.', 'history.empty': 'لم تُشغَّل أي أداة بعد.', 'history.success': 'ناجح', 'history.error': 'فشل',
    'common.loading': 'جارٍ التحميل', 'common.system': 'النظام', 'common.category': 'الفئة', 'common.readOnly': 'قراءة فقط', 'common.local': 'محلي', 'common.settings': 'إعدادات', 'common.light': 'فاتح', 'common.dark': 'داكن', 'common.comfortable': 'مريح', 'common.compact': 'مضغوط', 'common.on': 'مفعّل', 'common.off': 'معطّل', 'common.noData': 'غير متاح', 'common.result': 'النتيجة', 'common.summary': 'الملخص', 'common.folder': 'المجلد',
    'tools.system-health.name': 'فحص صحة النظام', 'tools.system-health.description': 'قراءة المعالج والذاكرة والقرص ووقت التشغيل من Windows.', 'tools.smart-scan.name': 'فحص ذكي', 'tools.smart-scan.description': 'تقييم قراءة فقط لمساحة القرص والتنزيلات والملفات المؤقتة.', 'tools.disk-overview.name': 'نظرة الأقراص', 'tools.disk-overview.description': 'سعة الأقراص المحلية ومساحتها الحرة ونظام الملفات.', 'tools.large-files.name': 'الباحث عن الملفات الكبيرة', 'tools.large-files.description': 'اكتشاف الملفات الكبيرة في المجلد الذي تحدده.', 'tools.duplicate-files.name': 'الباحث عن التكرارات', 'tools.duplicate-files.description': 'يجمع بالحجم ثم يتحقق من SHA-256 قبل الإبلاغ.', 'tools.empty-folders.name': 'المجلدات الفارغة', 'tools.empty-folders.description': 'يعرض المجلدات الفارغة دون حذفها.', 'tools.downloads-inventory.name': 'جرد التنزيلات', 'tools.downloads-inventory.description': 'يفحص مجلد التنزيلات الحقيقي ويعرض أكبر ملفاته.', 'tools.organize-downloads-preview.name': 'معاينة تنظيم التنزيلات', 'tools.organize-downloads-preview.description': 'يعرض نقل الملفات إلى فئات دون تعديل أي ملف.', 'tools.organize-downloads-apply.name': 'تطبيق تنظيم التنزيلات', 'tools.organize-downloads-apply.description': 'ينقل الملفات المعاينة فقط بعد تأكيد صريح ويسجل عملية تراجع.', 'tools.organize-downloads-undo.name': 'تراجع عن تنظيم التنزيلات', 'tools.organize-downloads-undo.description': 'يعيد الملفات من آخر سجل تنظيم محدد.', 'tools.temp-cleanup-preview.name': 'معاينة الملفات المؤقتة', 'tools.temp-cleanup-preview.description': 'يعرض فقط الملفات المؤهلة للمراجعة، دون تنظيف.', 'tools.startup-items.name': 'عناصر بدء التشغيل', 'tools.startup-items.description': 'قراءة عناصر Run الخاصة بالمستخدم والنظام.', 'tools.installed-apps.name': 'التطبيقات المثبتة', 'tools.installed-apps.description': 'جرد مصادر Uninstall المسجلة في Windows.', 'tools.network-diagnostics.name': 'تشخيص الشبكة', 'tools.network-diagnostics.description': 'واجهات الشبكة وعناوين IP وخوادم DNS المهيأة.', 'tools.hardware-inventory.name': 'معلومات العتاد', 'tools.hardware-inventory.description': 'قراءة معلومات CPU وGPU وBIOS المتاحة من Windows.', 'tools.event-warnings.name': 'تحذيرات الأحداث', 'tools.event-warnings.description': 'أخطاء وتحذيرات System لآخر سبعة أيام.', 'tools.file-hash.name': 'بصمة الملف', 'tools.file-hash.description': 'حساب SHA-256 أو SHA-512 لملف يختاره المستخدم.'
  },
  en: {
    'app.name': 'KNOuX SmartOrganizer', 'app.tagline': 'Private, local-first Windows utility', 'nav.home': 'Home', 'nav.scan': 'Smart Scan', 'nav.storage': 'Storage', 'nav.files': 'Files', 'nav.cleanup': 'Cleanup', 'nav.startup': 'Startup', 'nav.apps': 'Applications', 'nav.system': 'System', 'nav.network': 'Network', 'nav.hardware': 'Hardware', 'nav.history': 'History', 'nav.settings': 'Settings',
    'home.title': 'Device overview', 'home.subtitle': 'Measured local Windows data, with no fabricated results.', 'home.scan': 'Run Smart Scan', 'home.health': 'System health', 'home.ready': 'Ready to scan', 'home.offline': 'Core features work with no internet connection', 'home.memory': 'Memory usage', 'home.storage': 'System drive space', 'home.uptime': 'Uptime', 'home.cpu': 'Processor',
    'tools.title': 'Available tools', 'tools.search': 'Search a tool or category', 'tools.run': 'Run tool', 'tools.chooseFolder': 'Choose folder', 'tools.journal': 'Undo journal ID', 'confirm.organize': 'I reviewed the preview and confirm the listed file moves only.', 'tools.defaultFolder': 'Default: user home folder', 'tools.noSelection': 'Select a tool to review and run it.', 'tools.openHistory': 'Open history', 'tools.requiresFolder': 'A folder is required', 'tools.hashFile': 'Choose a file to calculate',
    'operation.title': 'Operation center', 'operation.ready': 'No active operation', 'operation.cancel': 'Cancel operation', 'operation.complete': 'Operation completed', 'operation.failed': 'Operation failed', 'operation.empty': 'Real operations will appear here while they run.', 'operation.items': 'Result items',
    'settings.title': 'Settings', 'settings.subtitle': 'Settings are saved locally. Usage analytics and crash reports are off by default.', 'settings.language': 'Application language', 'settings.theme': 'Theme', 'settings.density': 'Interface density', 'settings.motion': 'Reduce motion', 'settings.largeFile': 'Large-file threshold', 'settings.duplicate': 'Minimum duplicate size', 'settings.closeTray': 'Close to tray', 'settings.saved': 'Settings saved',
    'history.title': 'Operation history', 'history.subtitle': 'Real, locally stored outcomes with no sample results.', 'history.empty': 'No tool has been run yet.', 'history.success': 'Success', 'history.error': 'Failed',
    'common.loading': 'Loading', 'common.system': 'System', 'common.category': 'Category', 'common.readOnly': 'Read-only', 'common.local': 'Local', 'common.settings': 'Settings', 'common.light': 'Light', 'common.dark': 'Dark', 'common.comfortable': 'Comfortable', 'common.compact': 'Compact', 'common.on': 'On', 'common.off': 'Off', 'common.noData': 'Unavailable', 'common.result': 'Result', 'common.summary': 'Summary', 'common.folder': 'Folder',
    'tools.system-health.name': 'System health', 'tools.system-health.description': 'Read CPU, memory, storage, and uptime from Windows.', 'tools.smart-scan.name': 'Smart Scan', 'tools.smart-scan.description': 'Read-only review of storage pressure, Downloads, and temporary files.', 'tools.disk-overview.name': 'Disk overview', 'tools.disk-overview.description': 'Local drive capacity, free space, and filesystem.', 'tools.large-files.name': 'Large files finder', 'tools.large-files.description': 'Find large files in a folder you choose.', 'tools.duplicate-files.name': 'Duplicate finder', 'tools.duplicate-files.description': 'Groups by size then verifies with SHA-256 before reporting.', 'tools.empty-folders.name': 'Empty folders', 'tools.empty-folders.description': 'Lists empty folders without deleting them.', 'tools.downloads-inventory.name': 'Downloads inventory', 'tools.downloads-inventory.description': 'Scans the real Downloads folder and lists its largest files.', 'tools.organize-downloads-preview.name': 'Downloads organization preview', 'tools.organize-downloads-preview.description': 'Shows planned category moves without changing any file.', 'tools.organize-downloads-apply.name': 'Apply Downloads organization', 'tools.organize-downloads-apply.description': 'Moves previewed files only after explicit confirmation and creates an undo journal.', 'tools.organize-downloads-undo.name': 'Undo Downloads organization', 'tools.organize-downloads-undo.description': 'Restores files from a selected organization journal.', 'tools.temp-cleanup-preview.name': 'Temporary files preview', 'tools.temp-cleanup-preview.description': 'Lists reviewable temporary files only; it does not clean.', 'tools.startup-items.name': 'Startup items', 'tools.startup-items.description': 'Reads user and machine Run entries.', 'tools.installed-apps.name': 'Installed applications', 'tools.installed-apps.description': 'Inventories registered Windows uninstall sources.', 'tools.network-diagnostics.name': 'Network diagnostics', 'tools.network-diagnostics.description': 'Network interfaces, IP addresses, and configured DNS.', 'tools.hardware-inventory.name': 'Hardware inventory', 'tools.hardware-inventory.description': 'Reads CPU, GPU, and BIOS information available in Windows.', 'tools.event-warnings.name': 'Event warnings', 'tools.event-warnings.description': 'System warnings and errors from the last seven days.', 'tools.file-hash.name': 'File hash', 'tools.file-hash.description': 'Calculate SHA-256 or SHA-512 for a file you choose.'
  }
};

export function direction(locale: Locale) { return locale === 'ar' ? 'rtl' : 'ltr'; }
